---
title: "Schedule"
sidebar: false
toc: false
page-layout: full
freeze: false
---

::: {.schedule-page}

Here's your roadmap for the semester!

- [**Content**](/content/index.html) ({{< fa book-open-reader >}}): This page contains the readings, slides, and recorded lectures for the topic. Read and watch these first.

- [**Lesson**](/lesson/index.html) ({{< fa chalkboard-teacher >}}): This page contains an interactive lesson that teaches you the principles and code you need to know. Go through these after doing the content.

- [**Example**](/example/index.html) ({{< fa laptop-code >}}): This page contains fully annotated R code that you can use as a reference for creating your own visualizations. This is only a reference page—you don’t have to necessarily do anything here. Each section also contains videos of me live coding the examples so you can see what it looks like to work with R in real time. This page will be *very* helpful as you work on your assignments.

- [**Assignment**](/assignment/index.html) ({{< fa pen-ruler >}}): This page contains the instructions for either the session exercise (1–3 brief tasks), or for the two mini projects and final project. **Assignments are due by 11:59 PM on the Monday after their corresponding sessions.** That’s confusing in sentence form—see the schedule table below to see how it works.

:::::: {.row .d-flex .justify-content-center}
::::: {.col-12 .col-sm-10 .col-md-6}
:::: {.card .bg-danger .text-white}
::: {.card-body}

**tl;dr**: You should follow this general process for each session:

- Do everything on the content page ({{< fa book-open-reader >}})
- Work through the lesson page ({{< fa chalkboard-teacher >}})
- Complete the assignment ({{< fa pen-ruler >}}) while referencing the example ({{< fa laptop-code >}})

:::
::::
:::::
::::::

---

### Week 1: Syllabus Day &amp; Stylized Facts of Cities

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Tuesday, 01/26</td>
<td>Syllabus day</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/01-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="/urban-economics-syllabus.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>Tuesday, 01/26</td>
<td>Installing R &amp; Rstudio</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/01-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://rstudio-education.github.io/hopr/starting.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>Tuesday, 01/26</td>
<td>Installing Rmarkdown</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/01-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://bookdown.org/yihui/rmarkdown/installation.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>Thursday, 01/28</td>
<td>Stylized Urban Facts</td>
<td><a href="/lectures/01-stylized-facts.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/01-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>Thursday, 01/28</td>
<td>Intro to tidyverse</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/01-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab1.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 2: Agglomeration Forces

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Tuesday, 02/02</td>
<td>Why cities?</td>
<td><a href="/lectures/02-agglomeration.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/02-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.philadelphiafed.org/-/media/frbp/assets/economy/articles/business-review/2014/q2/brq214_paper_trail.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=-yUHoU0MKgI" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
<tr>
<td>Thursday, 02/04</td>
<td>Dataviz with ggplot2</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/02-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab2.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 3: Monocentric City Model I

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>02/09-02/11</td>
<td>The Monocentric City Model</td>
<td><a href="/lectures/03-monocentric-model-I.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/03-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.philadelphiafed.org/-/media/frbp/assets/economy/articles/economic-insights/2017/q1/eiq117_making-sense-of-urban-patterns.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 4: Monocentric City Model II &amp; Regulation

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Tuesday, 02/16</td>
<td>The Monocentric City Model - Extensions</td>
<td><a href="/lectures/04-monocentric-model-II.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/04-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>Thursday, 02/18</td>
<td>Sprawl &amp; Regulation</td>
<td><a href="/lectures/04-monocentric-model-II.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/04-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.bloomberg.com/news/features/2019-08-29/the-commuting-principle-that-shaped-urban-history" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.nytimes.com/2018/12/19/realestate/levittown-ny-the-original-starter-community.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=WpO3qRYn52A" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 5: Growing and Declining Cities &amp; The Great Divergence

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>02/23-02/25</td>
<td>Urban Growth and Decline &amp; The Great Divergence</td>
<td><a href="/lectures/05-great-divergence.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/05-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.theatlantic.com/ideas/archive/2020/12/life-simpsons-no-longer-attainable/617499/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.richmondfed.org/-/media/richmondfedorg/publications/research/econ_focus/2019/q1/interview.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.nytimes.com/2011/05/18/technology/18talent.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=xENJrNylRCg&amp;t=5s" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
<tr>
<td>Thursday, 02/25</td>
<td>Tidycensus</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/05-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab3.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><a href="https://walker-data.com/tidycensus/articles/basic-usage.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 6: Spatial Equilibrium Across Cities

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>03/02-03/04</td>
<td>Rosen-Roback Model</td>
<td><a href="/lectures/06-rosen-roback.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/06-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.fool.com/the-ascent/research/10-best-cities-high-salaries-low-cost-living/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://microeconomicinsights.org/causes-consequences-us-workers-diverging-locations-skill/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.bloomberg.com/news/articles/2015-06-29/a-new-index-maps-the-quality-of-life-for-2-000-u-s-neighborhoods" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.hks.harvard.edu/sites/default/files/centers/taubman/files/sunbelt.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
<tr>
<td>03/02-03/04</td>
<td>Mapping with tmap</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/06-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab4.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 7: Midterm Week

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Week 7</td>
<td>Midterm Week</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/07-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 8: Urban Transportation

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>03/16-03/18</td>
<td>Urban Transportation</td>
<td><a href="/lectures/07-transportation.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/08-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.bloomberg.com/news/articles/2016-06-02/report-the-relationship-between-subways-and-urban-growth" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://theconversation.com/london-congestion-charge-what-worked-what-didnt-what-next-92478#:~:text=The%20charge%20covers%20a%2021km%C2%B2,people%20can%20travel%20for%20free." target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.resourcesmag.org/common-resources/the-fundamental-law-of-road-congestion-and-its-implications-for-transportation-policy/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=clAaebwmdzw" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 9: Housing

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Tuesday, 03/23</td>
<td>Housing Demand and Tenure Choice</td>
<td><a href="/lectures/08-housing-demand.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/09-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.forbes.com/sites/forbesrealestatecouncil/2020/03/31/understanding-real-estate-tax-benefits-depreciation-accelerated-depreciation-bonus-depreciation/#7a3df2a6495c" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.philadelphiafed.org/-/media/frbp/assets/economy/articles/economic-insights/2020/q2/eiq220-house-prices.pdf?la=en" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?reload=9&amp;v=aFYlgqv3T-w&amp;feature=emb_title" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
<tr>
<td>Thursday, 03/25</td>
<td>Housing Policies</td>
<td><a href="/lectures/09-housing-policy.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/09-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.nytimes.com/2017/09/06/opinion/housing-regulations-us-economy.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.theatlantic.com/business/archive/2015/08/more-americans-are-living-in-slums/400832/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><a href="https://freakonomics.com/podcast/rent-control/" target="_blank"><i class="fa-solid fa-microphone-alt fa-lg"></i></a></td>
<td><a href="https://www.youtube.com/watch?v=yRq1AhFAN-4" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 10: Local Government

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>03/30-04/01</td>
<td>Tiebout Model</td>
<td><a href="/lectures/10-local-government.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/10-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=hA2z-X31IvI" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 11: Lab Quiz Week

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Tuesday, 04/06</td>
<td>Review Session</td>
<td><font color="#e9ecef"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></font></td><td><a href="/content/11-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/labreview.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-book-reader fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><font color="#e9ecef"><i class="fab fa-youtube fa-lg"></i></font></td>
</tr>
</tbody>
</table>

### Week 12: Neighborhood Choice

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>04/15-04/20</td>
<td>Neighborhood Choice</td>
<td><a href="/lectures/11-neighborhood-choice.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/12-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab5.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><a href="https://cityobservatory.org/wp-content/uploads/2018/06/ADMIN_Report_18June.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://ncase.me/polygons/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="/american_ghetto.pdf" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.epi.org/publication/racial-segregation-continues-intensifies/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fa-solid fa-microphone-alt fa-lg"></i></font></td>
<td><a href="https://www.youtube.com/watch?v=4c9JQbySRxg" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 13: Neighborhood Effects

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>Thursday, 04/22</td>
<td>Neighborhood Effects</td>
<td><a href="/lectures/12-neighborhood-effects.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/13-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><font color="#e9ecef"><i class="fab fa-r-project fa-lg"></i></font></td>
<td><a href="https://www.nytimes.com/2015/05/04/upshot/an-atlas-of-upward-mobility-shows-paths-out-of-poverty.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><a href="https://www.npr.org/transcripts/756028025" target="_blank"><i class="fa-solid fa-microphone-alt fa-lg"></i></a></td>
<td><a href="https://www.chicagoideas.com/videos/neighborhood-effects-and-the-contemporary-city" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>

### Week 14: Exploratory Spatial Data Analysis (ESDA)

<table class="schedule-table table">
<thead>
<tr>
<th>Date</th>
<th>Topic</th>
<th>Lecture Notes</th><th>Content</th>
<th>R labs</th>
<th>Readings</th>
<th>Podcast</th>
<th>Videos</th>
</tr>
</thead>
<tbody>
<tr>
<td>04/27-04/29</td>
<td>ESDA</td>
<td><a href="/lectures/13-esda.html"><i class="fa-solid fa-chalkboard-teacher fa-lg"></i></a></td><td><a href="/content/14-content.html"><i class="fa-solid fa-book-open-reader fa-lg"></i></a></td>
<td><a href="/labs/lab6.html"><i class="fab fa-r-project fa-lg"></i></a></td>
<td><a href="https://www.ph.ucla.edu/epi/snow/broadstreetpump.html#:~:text=In%20the%201854%20London%20epidemic,in%20the%20kingdom%22%20broke%20out" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.city-journal.org/cities-and-pandemics-have-long-history" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://nypost.com/2020/08/17/nyc-is-dead-forever-heres-why-james-altucher/" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a> <a href="https://www.nytimes.com/2020/08/24/opinion/jerry-seinfeld-new-york-coronavirus.html" target="_blank"><i class="fa-solid fa-book-reader fa-lg"></i></a></td>
<td><a href="https://freakonomics.com/podcast/urban-flight-part-1/" target="_blank"><i class="fa-solid fa-microphone-alt fa-lg"></i></a> <a href="https://freakonomics.com/podcast/pima-john-donohue/" target="_blank"><i class="fa-solid fa-microphone-alt fa-lg"></i></a></td>
<td><a href="https://www.youtube.com/watch?v=8C2jAuSl1Ak" target="_blank"><i class="fab fa-youtube fa-lg"></i></a></td>
</tr>
</tbody>
</table>


:::
