---
title: "Final Project"
---

## Final Project Guidelines SP21

### Preliminaries

- **Due 05/14/2021, 11:59 pm** (submission on Moodle). There will be only one submission per group, and each group must have 3-4 members
- Form groups and choose the [metro area](https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas) before April 22! Put the name of your groupmates and the selected metro in the spreadsheet to secure your first choice. Different groups cannot work with the same MSA.
- [Here](https://guerramarcelino.github.io/Econ414/Rlabs/finalprojectSP21) you find all the code you need to get the American Community Survey data from 2008-2012 and 2015-2019 relative to neighborhoods (census tracts) within a MSA. This is an example for Washington-Arlington-Alexandria, and you need to adapt the code for your choice of metropolitan area.
- [Here](https://drive.google.com/file/d/1w3fNOTJskM7qlPkn9Ueajir-mPv3F7Qh/view?usp=sharing) you find a template for the Final Project (if you want to knit the .rmd to HTML).

### Short-term changes in neighborhood characteristics

Using ACS 5-years 2008-2012 and 2015-2019 data, you are required to perform the following, but feel free to explore additional paths:

1. Map poverty shares and minority shares (non-whites) in 2019, and identify ghettos for the same period. [Calculate the Racial Dissimilarity Index](https://guerramarcelino.github.io/Econ414/Rlabs/lab5) (whites/non-whites) for 2012 and 2019. Is there any change in the RDI during the period?
1. Run the Moran’s I test/Moran’s scatterplot to assess the presence of spatial autocorrelation in poverty levels for 2019
1. Calculate the local Moran’s I and **map the clusters of urban poverty within the MSA** in 2019. Of course, before getting Moran’s I statistics, you need to construct a spatial weight matrix using either first-order contiguity or a distance-based criterion. Justify your choice of W matrix or use more than one type (if the Moran’s I are similar, you only need to report the result from one W matrix).
1. Check the overall poverty rate in the MSA and its change in the period 2012-2019. Identify tracts that moved from high poverty to low poverty and vice-versa. Also, explore the poverty levels in the surrounding area (i.e., the closest neighborhoods) of those tracts
1. Identify tracts where the median household income increased by 50% or more. Find out what happened with the shares of White, Black, Asian, Hispanic, foreign-born, the median year structure built, percentage of vacant units, the share of poverty, and share of bachelor’s degree or more. Any sign of gentrification? Are those neighborhoods located in the suburbs or close to downtown?
1. Make a table ([just like this one](https://guerramarcelino.github.io/Econ414/Rlabs/finalprojectSP21#making-tables)) for 2012 and 2019. Highlight what you think is important
1. Finally, [is there any tipping-like behavior?](https://guerramarcelino.github.io/Econ414/Rlabs/finalprojectSP21#is-there-any-tipping-like-behavior) Transform and plot the data adapting the provided code for Washington-Arlington-Alexandria

### Some tips

Read the report on neighborhood poverty from the [Economic Innovation Group](https://eig.org/neighborhood-poverty-project/neighborhood-turnaround#:~:text=For%20initially%20impoverished%20neighborhoods%2C%20persistent,64%20percent%20stayed%20high%20poverty.) focusing on the city case studies. That can help you to build your research.

You are free to structure your report as long as **i)** there is a logical sequence **ii)** it meets all the requirements specified above. Maps and scatter plots are not enough: you need to explain what you are doing and comment on all the results. Extra points will be given for concise writing with correctly displayed plots/results. Either `html` or `pdf` is fine. If you decide to knit to `html`, there is room for interactive maps and plots.

Have fun!
